[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache"
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
